# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-22 12:03
from __future__ import unicode_literals

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import apps.common.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True,
                                                      verbose_name='Publish date')),
                ('pos', models.PositiveSmallIntegerField(verbose_name='Position')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Title of Block')),
                ('text', models.TextField(verbose_name='Text of Block')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True,
                                                      verbose_name='Publish date')),
                ('pos', models.PositiveSmallIntegerField(verbose_name='Position')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Title of Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True,
                                                      verbose_name='Publish date')),
                ('pos', models.PositiveSmallIntegerField(unique=True, verbose_name='Position')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Title of Topic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='topic',
            field=apps.common.fields.CustomForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                      related_name='lessons', to='book.Topic', verbose_name='Topic'),
        ),
        migrations.AddField(
            model_name='block',
            name='lesson',
            field=apps.common.fields.CustomForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                      related_name='blocks', to='book.Lesson', verbose_name='Lesson'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set([('topic', 'pos')]),
        ),
    ]
