engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
  pep8:
    enabled: true
  radon:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - python:
      - javascript:
exclude_paths:
- "**/tests/**"
- "**/coverage/**"
- "**/internals/**"
- "**/server/**"
- "**/test_**"
