sudo: true
addons:
  postgresql: '9.5'

env:
  global:
  - DJANGO_SETTINGS_MODULE="config.settings.test"
  - PYTHONPATH="/home/travis/build/Alex-Just/uo"
  - PIP_USE_MIRRORS=true

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq build-essential gettext python-dev zlib1g-dev libpq-dev
  xvfb
- sudo apt-get install -qq libtiff4-dev libjpeg8-dev libfreetype6-dev liblcms1-dev
  libwebp-dev
- sudo apt-get install -qq graphviz-dev python-setuptools python3-dev python-virtualenv
  python-pip
- sudo apt-get install -qq firefox automake libtool libreadline6 libreadline6-dev
  libreadline-dev
- sudo apt-get install -qq libsqlite3-dev libxml2 libxml2-dev libssl-dev libbz2-dev
  wget curl llvm

matrix:
  include:

  - language: python
    python: 3.6.2
    install:
    - pip install -r backend/requirements/test.txt
    - pip install coveralls
    script:
    - coverage run backend/manage.py test backend
    after_success:
    - coveralls
    deploy:
      provider: heroku
      api_key:
        secure: $HEROKU_ENCRYPTED_API_KEY
      app: u-o
      on:
        repo: Alex-Just/uo
      strategy: git
      before_deploy:
      - find . -maxdepth 1 -type f -delete # remove all files in root folder
      - rm -rf frontend
      - rm -rf compose
      - cp -R ./backend/* .
      - rm -rf backend

  - language: node_js
    node_js: 8.2.1
    install:
    - cd ./frontend
    - yarn install
    - npm install -g codeclimate-test-reporter
    - npm install -g netlify-cli
    script:
    - npm test
    - npm run build
    after_success:
    - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN codeclimate-test-reporter < ./coverage/lcov.info
    - netlify deploy -s $NETLIFY_API_ID -t $NETLIFY_PERSONAL_ACCESS_TOKEN -p ./build
